pr:
  branches:
    include:
      - master
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true
  - bash: |
      python -m pip install poetry
      poetry install
    displayName: Install dependencies
  - bash: |
      python -m pytest
    displayName: Run tests